export default{
  MEMBER_LIST_SUCCESS: 'MEMBER_LIST_SUCCESS',
  MEMBER_LIST_FAILURE: 'MEMBER_LIST_FAILURE',
  MEMBER_DETAIL_SUCCESS: 'MEMBER_DETAIL_SUCCESS',
  MEMBER_DETAIL_FAILURE: 'MEMBER_DETAIL_FAILURE',
}