export default [
  {
      "login": "abadojack",
      "id": 8406752,
      "node_id": "MDQ6VXNlcjg0MDY3NTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8406752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abadojack",
      "html_url": "https://github.com/abadojack",
      "followers_url": "https://api.github.com/users/abadojack/followers",
      "following_url": "https://api.github.com/users/abadojack/following{/other_user}",
      "gists_url": "https://api.github.com/users/abadojack/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abadojack/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abadojack/subscriptions",
      "organizations_url": "https://api.github.com/users/abadojack/orgs",
      "repos_url": "https://api.github.com/users/abadojack/repos",
      "events_url": "https://api.github.com/users/abadojack/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abadojack/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "ah-med",
      "id": 30514950,
      "node_id": "MDQ6VXNlcjMwNTE0OTUw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/30514950?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ah-med",
      "html_url": "https://github.com/ah-med",
      "followers_url": "https://api.github.com/users/ah-med/followers",
      "following_url": "https://api.github.com/users/ah-med/following{/other_user}",
      "gists_url": "https://api.github.com/users/ah-med/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ah-med/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ah-med/subscriptions",
      "organizations_url": "https://api.github.com/users/ah-med/orgs",
      "repos_url": "https://api.github.com/users/ah-med/repos",
      "events_url": "https://api.github.com/users/ah-med/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ah-med/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "amos-o",
      "id": 16223682,
      "node_id": "MDQ6VXNlcjE2MjIzNjgy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/16223682?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amos-o",
      "html_url": "https://github.com/amos-o",
      "followers_url": "https://api.github.com/users/amos-o/followers",
      "following_url": "https://api.github.com/users/amos-o/following{/other_user}",
      "gists_url": "https://api.github.com/users/amos-o/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amos-o/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amos-o/subscriptions",
      "organizations_url": "https://api.github.com/users/amos-o/orgs",
      "repos_url": "https://api.github.com/users/amos-o/repos",
      "events_url": "https://api.github.com/users/amos-o/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amos-o/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "azeezolaniran2016",
      "id": 22840709,
      "node_id": "MDQ6VXNlcjIyODQwNzA5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/22840709?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/azeezolaniran2016",
      "html_url": "https://github.com/azeezolaniran2016",
      "followers_url": "https://api.github.com/users/azeezolaniran2016/followers",
      "following_url": "https://api.github.com/users/azeezolaniran2016/following{/other_user}",
      "gists_url": "https://api.github.com/users/azeezolaniran2016/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/azeezolaniran2016/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/azeezolaniran2016/subscriptions",
      "organizations_url": "https://api.github.com/users/azeezolaniran2016/orgs",
      "repos_url": "https://api.github.com/users/azeezolaniran2016/repos",
      "events_url": "https://api.github.com/users/azeezolaniran2016/events{/privacy}",
      "received_events_url": "https://api.github.com/users/azeezolaniran2016/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "bigzoo",
      "id": 25683935,
      "node_id": "MDQ6VXNlcjI1NjgzOTM1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/25683935?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bigzoo",
      "html_url": "https://github.com/bigzoo",
      "followers_url": "https://api.github.com/users/bigzoo/followers",
      "following_url": "https://api.github.com/users/bigzoo/following{/other_user}",
      "gists_url": "https://api.github.com/users/bigzoo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bigzoo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bigzoo/subscriptions",
      "organizations_url": "https://api.github.com/users/bigzoo/orgs",
      "repos_url": "https://api.github.com/users/bigzoo/repos",
      "events_url": "https://api.github.com/users/bigzoo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bigzoo/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "blackshady",
      "id": 26234445,
      "node_id": "MDQ6VXNlcjI2MjM0NDQ1",
      "avatar_url": "https://avatars3.githubusercontent.com/u/26234445?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/blackshady",
      "html_url": "https://github.com/blackshady",
      "followers_url": "https://api.github.com/users/blackshady/followers",
      "following_url": "https://api.github.com/users/blackshady/following{/other_user}",
      "gists_url": "https://api.github.com/users/blackshady/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/blackshady/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/blackshady/subscriptions",
      "organizations_url": "https://api.github.com/users/blackshady/orgs",
      "repos_url": "https://api.github.com/users/blackshady/repos",
      "events_url": "https://api.github.com/users/blackshady/events{/privacy}",
      "received_events_url": "https://api.github.com/users/blackshady/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "brianbirir",
      "id": 2263386,
      "node_id": "MDQ6VXNlcjIyNjMzODY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2263386?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/brianbirir",
      "html_url": "https://github.com/brianbirir",
      "followers_url": "https://api.github.com/users/brianbirir/followers",
      "following_url": "https://api.github.com/users/brianbirir/following{/other_user}",
      "gists_url": "https://api.github.com/users/brianbirir/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/brianbirir/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/brianbirir/subscriptions",
      "organizations_url": "https://api.github.com/users/brianbirir/orgs",
      "repos_url": "https://api.github.com/users/brianbirir/repos",
      "events_url": "https://api.github.com/users/brianbirir/events{/privacy}",
      "received_events_url": "https://api.github.com/users/brianbirir/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "ChigboIO",
      "id": 15727628,
      "node_id": "MDQ6VXNlcjE1NzI3NjI4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/15727628?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChigboIO",
      "html_url": "https://github.com/ChigboIO",
      "followers_url": "https://api.github.com/users/ChigboIO/followers",
      "following_url": "https://api.github.com/users/ChigboIO/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChigboIO/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChigboIO/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChigboIO/subscriptions",
      "organizations_url": "https://api.github.com/users/ChigboIO/orgs",
      "repos_url": "https://api.github.com/users/ChigboIO/repos",
      "events_url": "https://api.github.com/users/ChigboIO/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChigboIO/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "d3mola",
      "id": 25783086,
      "node_id": "MDQ6VXNlcjI1NzgzMDg2",
      "avatar_url": "https://avatars2.githubusercontent.com/u/25783086?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/d3mola",
      "html_url": "https://github.com/d3mola",
      "followers_url": "https://api.github.com/users/d3mola/followers",
      "following_url": "https://api.github.com/users/d3mola/following{/other_user}",
      "gists_url": "https://api.github.com/users/d3mola/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/d3mola/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/d3mola/subscriptions",
      "organizations_url": "https://api.github.com/users/d3mola/orgs",
      "repos_url": "https://api.github.com/users/d3mola/repos",
      "events_url": "https://api.github.com/users/d3mola/events{/privacy}",
      "received_events_url": "https://api.github.com/users/d3mola/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "jkanyua",
      "id": 24469235,
      "node_id": "MDQ6VXNlcjI0NDY5MjM1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/24469235?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jkanyua",
      "html_url": "https://github.com/jkanyua",
      "followers_url": "https://api.github.com/users/jkanyua/followers",
      "following_url": "https://api.github.com/users/jkanyua/following{/other_user}",
      "gists_url": "https://api.github.com/users/jkanyua/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jkanyua/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jkanyua/subscriptions",
      "organizations_url": "https://api.github.com/users/jkanyua/orgs",
      "repos_url": "https://api.github.com/users/jkanyua/repos",
      "events_url": "https://api.github.com/users/jkanyua/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jkanyua/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "kwakueshun",
      "id": 26971942,
      "node_id": "MDQ6VXNlcjI2OTcxOTQy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/26971942?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kwakueshun",
      "html_url": "https://github.com/kwakueshun",
      "followers_url": "https://api.github.com/users/kwakueshun/followers",
      "following_url": "https://api.github.com/users/kwakueshun/following{/other_user}",
      "gists_url": "https://api.github.com/users/kwakueshun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kwakueshun/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kwakueshun/subscriptions",
      "organizations_url": "https://api.github.com/users/kwakueshun/orgs",
      "repos_url": "https://api.github.com/users/kwakueshun/repos",
      "events_url": "https://api.github.com/users/kwakueshun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kwakueshun/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "muhozi",
      "id": 5815755,
      "node_id": "MDQ6VXNlcjU4MTU3NTU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5815755?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/muhozi",
      "html_url": "https://github.com/muhozi",
      "followers_url": "https://api.github.com/users/muhozi/followers",
      "following_url": "https://api.github.com/users/muhozi/following{/other_user}",
      "gists_url": "https://api.github.com/users/muhozi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/muhozi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/muhozi/subscriptions",
      "organizations_url": "https://api.github.com/users/muhozi/orgs",
      "repos_url": "https://api.github.com/users/muhozi/repos",
      "events_url": "https://api.github.com/users/muhozi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/muhozi/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "peteretelej",
      "id": 2271973,
      "node_id": "MDQ6VXNlcjIyNzE5NzM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2271973?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/peteretelej",
      "html_url": "https://github.com/peteretelej",
      "followers_url": "https://api.github.com/users/peteretelej/followers",
      "following_url": "https://api.github.com/users/peteretelej/following{/other_user}",
      "gists_url": "https://api.github.com/users/peteretelej/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/peteretelej/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/peteretelej/subscriptions",
      "organizations_url": "https://api.github.com/users/peteretelej/orgs",
      "repos_url": "https://api.github.com/users/peteretelej/repos",
      "events_url": "https://api.github.com/users/peteretelej/events{/privacy}",
      "received_events_url": "https://api.github.com/users/peteretelej/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "raheemazeezabiodun",
      "id": 16730330,
      "node_id": "MDQ6VXNlcjE2NzMwMzMw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/16730330?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raheemazeezabiodun",
      "html_url": "https://github.com/raheemazeezabiodun",
      "followers_url": "https://api.github.com/users/raheemazeezabiodun/followers",
      "following_url": "https://api.github.com/users/raheemazeezabiodun/following{/other_user}",
      "gists_url": "https://api.github.com/users/raheemazeezabiodun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raheemazeezabiodun/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raheemazeezabiodun/subscriptions",
      "organizations_url": "https://api.github.com/users/raheemazeezabiodun/orgs",
      "repos_url": "https://api.github.com/users/raheemazeezabiodun/repos",
      "events_url": "https://api.github.com/users/raheemazeezabiodun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raheemazeezabiodun/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "seyi-adeleke",
      "id": 7271210,
      "node_id": "MDQ6VXNlcjcyNzEyMTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7271210?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/seyi-adeleke",
      "html_url": "https://github.com/seyi-adeleke",
      "followers_url": "https://api.github.com/users/seyi-adeleke/followers",
      "following_url": "https://api.github.com/users/seyi-adeleke/following{/other_user}",
      "gists_url": "https://api.github.com/users/seyi-adeleke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/seyi-adeleke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/seyi-adeleke/subscriptions",
      "organizations_url": "https://api.github.com/users/seyi-adeleke/orgs",
      "repos_url": "https://api.github.com/users/seyi-adeleke/repos",
      "events_url": "https://api.github.com/users/seyi-adeleke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/seyi-adeleke/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "Sharonsyra",
      "id": 15943349,
      "node_id": "MDQ6VXNlcjE1OTQzMzQ5",
      "avatar_url": "https://avatars2.githubusercontent.com/u/15943349?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sharonsyra",
      "html_url": "https://github.com/Sharonsyra",
      "followers_url": "https://api.github.com/users/Sharonsyra/followers",
      "following_url": "https://api.github.com/users/Sharonsyra/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sharonsyra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sharonsyra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sharonsyra/subscriptions",
      "organizations_url": "https://api.github.com/users/Sharonsyra/orgs",
      "repos_url": "https://api.github.com/users/Sharonsyra/repos",
      "events_url": "https://api.github.com/users/Sharonsyra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sharonsyra/received_events",
      "type": "User",
      "site_admin": false
  },
  {
      "login": "swaibat",
      "id": 41104288,
      "node_id": "MDQ6VXNlcjQxMTA0Mjg4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/41104288?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/swaibat",
      "html_url": "https://github.com/swaibat",
      "followers_url": "https://api.github.com/users/swaibat/followers",
      "following_url": "https://api.github.com/users/swaibat/following{/other_user}",
      "gists_url": "https://api.github.com/users/swaibat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/swaibat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/swaibat/subscriptions",
      "organizations_url": "https://api.github.com/users/swaibat/orgs",
      "repos_url": "https://api.github.com/users/swaibat/repos",
      "events_url": "https://api.github.com/users/swaibat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/swaibat/received_events",
      "type": "User",
      "site_admin": false
  }
]